### ISSUE TITLE
Windows builds could obtain CommandLine from PEB instead of leaking memory

### ISSUE THREAD

**Issue by Frago9876543210** [dtolnay/argv#5] opened 2021-06-27 15:19 UTC
PEB address can be found like that:
```asm
mov rax, gs:[0x60]
```

`0x60` is offset to `PEB` from `TEB`. For example `ntapi` crate implements some functions that calculates that address for x86 and x64 builds

```c
typedef struct _PEB
{                                                                 /* win32/win64 */
    BOOLEAN                      InheritedAddressSpace;             /* 000/000 */
    BOOLEAN                      ReadImageFileExecOptions;          /* 001/001 */
    BOOLEAN                      BeingDebugged;                     /* 002/002 */
    BOOLEAN                      SpareBool;                         /* 003/003 */
    HANDLE                       Mutant;                            /* 004/008 */
    HMODULE                      ImageBaseAddress;                  /* 008/010 */
    PPEB_LDR_DATA                LdrData;                           /* 00c/018 */
    RTL_USER_PROCESS_PARAMETERS *ProcessParameters;                 /* 010/020 */
};
```

```c
typedef struct _RTL_USER_PROCESS_PARAMETERS
{
    ULONG               AllocationSize;
    ULONG               Size;
    ULONG               Flags;
    ULONG               DebugFlags;
    HANDLE              ConsoleHandle;
    ULONG               ConsoleFlags;
    HANDLE              hStdInput;
    HANDLE              hStdOutput;
    HANDLE              hStdError;
    CURDIR              CurrentDirectory;
    UNICODE_STRING      DllPath;
    UNICODE_STRING      ImagePathName;
    UNICODE_STRING      CommandLine; //<--------------
};
 ```
https://github.com/wine-mirror/wine/blob/1aff1e6a370ee8c0213a0fd4b220d121da8527aa/include/winternl.h#L186

**Comment by dtolnay** [comment] 2021-06-27 16:02
I would accept a PR to implement this.

**Comment by morr0ne** [comment] 2022-07-30 12:23
I ran across this issue while implementing my own library and I think it might not be possible, or at least not without allocating. The problem is that even after successfully retrieving the PEB data, the CommandLine field is nothing more than an utf-16 encoded string. On unix like systems we actually get the args but on windows we would need to parse that string ourselves which I don't think is possible without allocating memory.

Below is what I came up with to retrieve the String using nothing more than `core` and the windows crate (making this no_std compatible)

```rust
use core::{
    arch::asm,
    ptr::{null, null_mut},
};

#[cfg(all(target_os = "windows", target_env = "msvc"))]
use windows::{core::PWSTR, Win32::System::Threading::PEB};

#[cfg(all(target_os = "windows", target_env = "msvc"))]
static mut ARGS: PWSTR = PWSTR(null_mut());

#[cfg(all(target_os = "windows", target_env = "msvc"))]
#[used]
#[link_section = ".CRT$XCU"]
static ARGS_INIT: extern "C" fn() = {
    extern "C" fn init_args() {
        let peb: *mut PEB;
        unsafe {
            asm!(
              "mov {}, gs:[0x60]",
              out(reg) peb,
              options(pure, nomem, nostack)
            );
        }

        unsafe { ARGS = (*(*peb).ProcessParameters).CommandLine.Buffer }
    }
    init_args
};
``` 

While this works great but we still only end up with a [PWSTR](https://microsoft.github.io/windows-docs-rs/doc/windows/core/struct.PWSTR.html) which can't be easily (or maybe at all) parsed into args without allocating at very least two Vectors.

More resources:
https://docs.microsoft.com/en-us/archive/blogs/larryosterman/the-windows-command-line-is-just-a-string
https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?view=msvc-160#parsing-c-command-line-arguments

You can also see here how the standard library handles it: 
https://github.com/rust-lang/rust/blob/760d8a2cb169974971cb54302c857bfed0070f6e/library/std/src/sys/windows/args.rs

They basically implement a custom parser that simulates c/c++ args like on posix compliant systems.

**Comment by dtolnay** [comment] 2022-07-30 15:29
Ah okay; thanks for the investigation and the writeup! I'll close this then.

**Closed by dtolnay** 2022-07-30 15:29 UTC
Labels: help wanted, windows
